# fly.toml app configuration file generated for ramp-fun-indexer on 2024-06-30T07:53:36+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ramp-fun-indexer"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
